[workspace]
members = ["gengo", "gengo-bin", "samples-test"]
resolver = "2"

[workspace.package]
description = "Get the language distribution stats of your repository"
version = "0.9.1"
edition = "2021"
repository = "https://github.com/spenserblack/gengo"
readme = "README.md"
license = "MIT OR Apache-2.0"

keywords = ["language-statistics"]
